fpm:
  image: deluxo/php7.17-fpm
  volumes:
    - /var/www:/var/www
#  ports:
#    - "9000:9000"
fpm2:
  image: deluxo/php5.6.3
  volumes:
    - /var/www:/var/www
#  ports:
#    - "9001:9000"
nginx:
  image: nginx
  links:
    - fpm
    - fpm2
  ports:
    - 80:80
    - 443:443
    - 880:880
  volumes:
    - /var/www/:/var/www/
    - /opt/docker/logs/nginx/logs/:/var/log/nginx/
    - /opt/docker/conf/nginx/conf.d/:/etc/nginx/conf.d
    - /opt/docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
redis:
  image: redis
  ports:
    - 6379:6379
node_front:
  image: deluxo/nodejs
#  command: npm i
  command: npm run dev
  restart: always
#  mem_limit: 128m
  ports:
    - 1111:1111
  volumes:
    - /var/www/ssfront:/usr/src/app

